spring.application.name=journey

# 資料庫連線設定
spring.datasource.url=jdbc:sqlserver://localhost:1433;database=EEIT199travel;encrypt=false;useUnicode=true;characterEncoding=UTF-8;
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
# 以下兩行屬性值的地方請檢視者改成自己的SQL帳號密碼
spring.datasource.username=sa
spring.datasource.password=Terry890424$

# ── Log 等級 ─────────────────────
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type=TRACE

# JPA / Hibernate 設定
spring.jpa.hibernate.ddl-auto=validate

# spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect
# spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.jpa.hibernate.naming.implicit-strategy=org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyHbmImpl

# 設定預設時區與格式
spring.jackson.date-format=yyyy-MM-dd
spring.jackson.time-zone=Asia/Taipei

logging.level.org.hibernate.tool.hbm2ddl=debug

#  Security暫時放行全部 API（測試用）
# spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

# CORS 設定
spring.web.cors.allowed-origins=http://localhost:5173,http://localhost:3000
spring.web.cors.allowed-methods=GET,POST,PUT,DELETE,OPTIONS,PATCH
spring.web.cors.allowed-headers=*
spring.web.cors.allow-credentials=true

# vscode 輸出 ANSI 彩色
spring.output.ansi.enabled=ALWAYS

# =========== Cache ===========
# 使用 Caffeine
spring.cache.type=caffeine                   
# 想快取的名稱
# spring.cache.cache-names=bedTypes,lodgingTypes,roomFacilities   
# 設定 Caffeine 快取 12 小時有效
spring.cache.caffeine.spec=expireAfterWrite=12h 



# 自訂變數 #
# 使用者上傳檔案的資料夾路徑，部署時需要修改成絕對路徑
file.upload-dir=uploads/

# 檔案上傳配置
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
spring.servlet.multipart.file-size-threshold=2KB


# LINE Pay token (Sandbox)
linepay.channel-id= 2007569221
linepay.channel-secret= 173bdf58e6f12aebc8795fdc60901202
linepay.api.base-url= https://sandbox-api-pay.line.me
linepay.confirm-url= http://localhost:8080/api/linepay/confirm
linepay.cancel-url= http://localhost:5173/checkout
linepay.return-url= http://localhost:5173/order-result

# 綠界支付配置 (測試環境)
ecpay.merchant-id=2000132
ecpay.hash-key=5294y06JbISpM5x9
ecpay.hash-iv=v77hoKGq4kWxNNIS
ecpay.api.base-url=https://payment-stage.ecpay.com.tw
ecpay.notify-url=http://localhost:8080/ecpay/notify
ecpay.result-url=http://localhost:8080/ecpay/result
ecpay.cancel-url=http://localhost:8080/ecpay/cancel

# debug用，可以讓spring在console輸出日誌 
# logging.level.org.springframework.security=DEBUG
# logging.level.org.hibernate.SQL=DEBUG
# logging.level.org.hibernate.type.descriptor.sql=TRACE